sonar.projectKey=gabrielepinese_PyStore
sonar.organization=gabrielepinese

sonar.sources=backend,frontend/src
sonar.tests=backend,frontend/src
sonar.test.inclusions=**/tests/**,**/*.spec.ts

sonar.python.coverage.reportPaths=coverage-reports/coverage-auth-service/coverage.xml,coverage-reports/coverage-products-service/coverage.xml
sonar.javascript.lcov.reportPaths=coverage-reports/coverage-frontend/lcov.info
